name: Solar System Unit Tests

on:
    workflow_dispatch: 
    push: 

env:  
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} 

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependencies and Run Unit Tests
              run: |
                npm install
                npm test
            
            - name: Archive Test Results
              uses: actions/upload-artifact@v4
              with:
                name: Mocha-Test-Result
                path: test-results.xml