name: Solar System Unit Tests

on:
    workflow_dispatch: 
    push: 

env:  
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} 

jobs:
    unit-testing:
        strategy:
          matrix:
            node-version: [20]
            os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Install NodeJS ${{ matrix.node-version }} on ${{ matrix.os }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install Dependencies and Run Unit Tests
              run: |
                npm install
                npm test
            
            - name: Archive Test Results
              uses: actions/upload-artifact@v4
              with:
                name: Mocha-Test-Result-${{ matrix.node-version}}-${{ matrix.os }}
                path: test-results.xml
    
    code-coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
    
            - name: Setup NodeJS version - 20
              uses: actions/setup-node@v3
              with:
                node-version: 20
            
            - name: Install Dependencies and Run code coverage
              run: |
                  npm install
                  npm run coverage
              continue-on-error: true
    
            - name: Archive Test Result
              uses: actions/upload-artifact@v3
              with:
                name: Code-Coverage-Result
                path: coverage
                retention-days: 5