name: Env Variables

on:
    workflow_dispatch: 
    push: 

env:  
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} 

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        outputs:
            value1: ${{ steps.step1.outputs.var1 }}
        steps:
            - name: Set Environment Variable
              id: step1
              run: |
                echo "var1=Bokkale" >> "$GITHUB_ENV"
                echo "var1=Bokkale" >> "$GITHUB_OUTPUT"
            
            - name: Print Environment Variable
              run: |
                echo $var1
                echo ${{ env.var1 }}
    get-value:
        runs-on: ubuntu-latest
        needs: unit-testing
        env:
          var1: ${{ needs.unit-testing.outputs.value1 }}
        steps:
            - name: Print Environment Var
              run: echo "Hello $var1"
            
